# Plaintext test credentials for this environment.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres
stringData:
  POSTGRES_USER: voize
  POSTGRES_PASSWORD: voize
