#!/usr/bin/env bash
# Generates apps/base/<app>/slo-rules.yaml (a VMRule) from apps/base/<app>/slo.yaml
# with Sloth. Everything shared by all apps' SLOs is set here: Sloth version,
# 28-day SLO period, MetricsQL validation, and SLI recording rules only.
# Drift check: scripts/slo-generate.sh && git diff --exit-code -- 'apps/base/*/slo-rules.yaml'
set -euo pipefail
cd "$(dirname "$0")/.."

for spec in apps/base/*/slo.yaml; do
  dir=$(dirname "$spec")
  app=$(basename "$dir") # the folder name is also the namespace
  # The spec goes in on stdin: a bind mount can miss a file an editor just replaced.
  rules=$(docker run --rm --interactive ghcr.io/slok/sloth:v0.16.0 generate \
    -i /dev/stdin \
    --default-slo-period=28d \
    --disable-default-slo-plugins \
    -s '{"id":"sloth.dev/contrib/validate_victoria_metrics/v1"}' \
    -s '{"id":"sloth.dev/core/sli_rules/v1"}' <"$spec")
  {
    echo "# Generated by scripts/slo-generate.sh from slo.yaml. Do not edit."
    echo "apiVersion: operator.victoriametrics.com/v1beta1"
    echo "kind: VMRule"
    echo "metadata:"
    echo "  name: $app-slo"
    echo "  namespace: $app"
    echo "spec:"
    sed -e '/^#/d' -e '/^---$/d' -e '/^$/d' -e 's/^/  /' <<<"$rules"
  } >"$dir/slo-rules.yaml"
  echo "wrote $dir/slo-rules.yaml"
done
