# Plaintext test credentials for this environment.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: backend-api
stringData:
  POSTGRES_USER: voize
  POSTGRES_PASSWORD: voize
